### ISSUE TITLE
The performance of ucudnn-Tensorflow gets worse

### ISSUE THREAD

**Issue by oscarriddle** [spcl/ucudnn#7]
ENV:
Tensorflow 1.14, CUDA10.0, cuDNN7.5.0, 

After compiled the ucudnn with Tensorflow 1.14, I tested the performance, the test model is InceptionV3, and I noticed the performance is about 10%~20% worse than original cudnn.

After trying to set different runtime environment variables, different batch sizes and tensorflow workspace limit. The performance of ucudnn-tensorflow is always worse than cudnn-tensorflow.

Perhaps this gap comes from the coding style efficiency, but after investigating the perfs matrix that returned by getAlgorithm of cudnn, the speed of GEMM methods are very similar to FFT or WINOGRAD, which confused me. Doesn't WINOGRAD/FFT should at least 2~3 times faster than GEMM at most cases?

Besides, I also checked the mechanism of  bfc_allocator of tensorflow, it will dynamically allocate needed workspace per each convolution and dynamically release that part of workspace. So the workspaces will not accumulates during session run. 

Would like to hear some advice from your side.

**Comment by tbennun** [comment]
Hey, thanks for reporting.

We are aware of TensorFlow's dynamic allocator, and in certain cases (where memory requirements allow choosing the fastest methods), it can pick the fastest algorithms per convolution.

However, ucudnn should not be that much slower than TensorFlow, because at the worst case it should choose the same algorithm as would have been chosen without dividing the minibatch.

FFT and Winograd based convolutions are both faster when certain sizes are used, i.e., very large kernels for FFT and 3x3 spatial dimensions for Winograd. It really depends on the problem dimensions. Quick question: are you using Tensor Cores for the computations?

Perhaps something needs to be updated in ucudnn to better support TF 1.14 or CUDNN 7.

**Comment by oscarriddle** [comment]
Hi @tbennun 

Thanks for your reply.

Ideally you are right, ucudnn shan't be much slower than cudnn in Tensorflow.

But I noticed Tensorflow doesn't count on the empirical estimated performance that returned from the query "cudnnFindConvolutionGenericAlgorithm()". Instead, Tensorflow measures the actual elapsed time of each convolution:

(in the cuda_dnn.cc):
```
port::Status CudnnSupport::DoConvolve(
.
.
.
  if (is_profiling) {
    timer.reset(new GpuTimer(parent_));  // NOLINT
    // The start and stop of the timer should be as close to the Cudnn call as
    // possible. It is still possible for other threads to issue workload on
    // to this stream. So it could take multiple profiling measurements.
    if (!timer->Init() || !timer->Start(AsGpuStream(stream))) {
      return port::Status(port::error::INTERNAL, "Failed to start timer");
    }
  }
.
.
.
  if (is_profiling) {
    if (!timer->Stop(AsGpuStream(stream))) {
      return port::Status(port::error::INTERNAL, "Failed to stop timer");
    }
    output_profile_result->set_algorithm(algorithm_desc);
    output_profile_result->set_elapsed_time_in_ms(
        timer->GetElapsedMilliseconds());
    output_profile_result->set_scratch_size(scratch_memory.size());
  }

  return port::Status::OK();

```
---------------------

Tensorflow uses cuEvent to measure convolution elapsed duration, and I compared the two methods, the empirical time and the elapsed time are very similar. Interesting...

For example:
```
perf.algo:1 perf.time:26.783 elapsed_time:25.4195
perf.algo:0 perf.time:57.2512 elapsed_time:57.7044
perf.algo:5 perf.time:174.406 elapsed_time:174.284

perf.algo:1 perf.time:14.7961 elapsed_time:14.8669
perf.algo:0 perf.time:22.8526 elapsed_time:21.6315
perf.algo:2 perf.time:26.3698 elapsed_time:26.6383
```
